# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPdO_318kX8df__WBcVCIxrW0A-hucUP
"""

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML
# First set up the figure, the axis, and the plot element we want to animate
fig, ax = plt.subplots()
ax.set_xlim(( 0, 2))
ax.set_ylim((-2, 2))
line, = ax.plot([], [], lw=2)
# initialization function: plot the background of each frame
def init():
 line.set_data([], [])
 return (line,)

def solve(N,Tf,alpha=1e-6,beta=5.6e-5,T_inf=50):
  hx=1/N
  ht=(hx**2)/(8*alpha)
  t = [0 for x in range(N)]
  un1 = -2*hx*beta*(0-T_inf**4)
  t.append(un1)
  for ti in range(int(Tf/ht)):
    tn = [0]
    for i in range(1,N):
      u1 = t[i] + alpha*ht/(hx**2)*(t[i+1]-2*t[i]+t[i-1])
      tn.append(u1)
    un1 = -2*hx*beta*(tn[-1]**4-T_inf**4)+tn[-2]
    tn.append(un1)
    t = tn
  return np.array(t)

t = solve(100,100000000)
x = np.array([x for x in range(101)])
plt.plot(x,t)

